# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdmi', '0003_site_browser_module_squashed_0005_auto_20170309_1113_squashed_0004_auto_20170309_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='browser_module',
            new_name='browser_path',
        ),
    ]
