# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdmi', '0004_auto_20170314_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebDAVServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.URLField()),
                ('login', models.CharField(max_length=200)),
                ('passwd', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='browser_webdav',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdmi.WebDAVServer'),
        ),
    ]
