# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdmi', '0005_auto_20170418_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
