# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdmi', '0006_site_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='root_container',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='site',
            name='browser_webdav',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdmi.WebDAVServer'),
        ),
    ]
