# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='provider_name',
            field=models.CharField(default='empty', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provider',
            name='client_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='provider',
            name='client_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='provider',
            name='client_secret',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='provider',
            name='openid_configuration',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='redirect_uri',
            field=models.URLField(blank=True),
        ),
    ]
