# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openid', '0004_provider_jwks_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='authorization_endpoint',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='provider',
            name='introspection_endpoint',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='provider',
            name='jwks_uri',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='provider',
            name='token_endpoint',
            field=models.URLField(),
        ),
    ]
