# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openid', '0006_provider_logo_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='userinfo_endpoint',
            field=models.URLField(default='https://iam-test.indigo-datacloud.eu/userinfo'),
            preserve_default=False,
        ),
    ]
