# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openid', '0007_provider_userinfo_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='introspection_endpoint',
            field=models.URLField(blank=True),
        ),
    ]
