# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openid', '0008_auto_20170214_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
